# Generated by Django 5.1 on 2024-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_compra_cantidad_remove_compra_codigo_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad_combustible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
